{{- $account := include "k8s-service-account.name" . -}}

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ $account }}
roleRef:
  apiGroup: {{ .Values.apiGroup | default "rbac.authorization.k8s.io" }}
  kind: ClusterRole
  name: {{ .Values.role }}
subjects:
- kind: ServiceAccount
  name: {{ $account }}
  namespace: {{ .Release.Namespace }}