{{- $accountName = .Values.role -}}

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $accountName }}

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ $accountName }}
roleRef:
  apiGroup: {{ .Values.apiGroup | default "rbac.authorization.k8s.io" }}
  kind: ClusterRole
  name: {{ .Values.role }}
subjects:
- kind: ServiceAccount
  name: {{ $accountName }}