apiVersion: v1
kind: Secret
metadata:
  # this name needs to be called out in jenkins values.yaml
  #
  name: jenkins-secrets
  labels: 
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
type: Opaque
data:
  {{- range $key, $value := .Values.secrets }}
    {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
  